name: Deploy

on:
  push:
    branches:
      - main
      
env:
  EXCLUDES: ".git .github conf/certbot/" 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with :
            path: ./object-api

        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.DEPLOYMENT_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

        - name: rsync deploy
          run: |
            exArgs=""
            for e in "${excludes[@]}"; do 
                exArgs+="--exclude ${e} "
            done
            echo $exArgs
            rsync -azv $exArgs -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" . patchwork@ewr-container-001.vwire.net:~/object-api/

        - name: restart container
          run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa patchwork@ewr-container-001.vwire.net 'cd object-api && docker compose up -d --build --force-recreate --no-deps'