map $host $ssl_cert {
    default "";
    object.patchwork.horse /etc/letsencrypt/live/object.patchwork.horse/fullchain.pem;
}

map $host $ssl_cert_key {
    default "";
    object.patchwork.horse /etc/letsencrypt/live/object.patchwork.horse/privkey.pem;
}